INSERT INTO USER(ID, EMAIL, PASSWORD, USERNAME, LAST_PASSWORD_RESET, VERSION) VALUES(SQX_USER.nextval, 'user@localhost.com', '{bcrypt}$2a$10$CbK.fXSYph91GI3HDIxl.exjnDGNvnujGEpwdI6xH490voVm7oT/q', 'user', NOW(), 0);

INSERT INTO USER_AUTHORITY(ID, USER_ID, AUTHORITY_ID) VALUES(SQX_USER_AUTHORITY.nextval, SQX_USER.currval, SQX_AUTHORITY.currval);
