jwt:
  header: Authorization
  secret: mySecret
  expiration: 3600
  route:
    authentication:
      path: /api/auth
      refresh: /api/refresh
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false

